version: '2'

networks:
    inside:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.254
                - subnet: "fd00:abcd:dcba:0001::/48"
                  gateway: "fd00:abcd:dcba:0001::0254"
    outside:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24
                  gateway: 172.16.0.254
                - subnet: "fd00:dead:beef:0001::/112"
                  gateway: "fd00:dead:beef:0001::0254"

services:
  client:
    environment:
        - TARGET_HOST=192.168.1.10
    image: repo.treescale.com/jbucyber/client:latest
    networks:
        outside:
            ipv4_address: 172.16.0.5
            ipv6_address: fd00:dead:beef:0001::5
        inside:
            ipv4_address: 192.168.1.201
            ipv6_address: fd00:abcd:dcba:0001::201
    volumes:
        - /data/jbucyber:/data:rw
  firewall:
    image: alpine:edge
    networks:
        inside:
        outside:
    volumes:
        - /data/jbucyber:/data:rw
  server:
    image: repo.treescale.com/jbucyber/server:latest
    networks:
        inside:
            ipv4_address: 192.168.1.10
            ipv6_address: fd00:abcd:dcba:0001::10
    volumes:
        - /data/jbucyber:/data:rw
