---

- hosts: localhost
  connection: local

  tasks:
    - include_vars: vars.yml

#    - name: Getting current AWS ECR credentials
#      shell: "aws ecr get-login --region us-east-1"
#      register: ecr_results

    - set_fact:
          date_tag="{{ansible_date_time.year}}{{ ansible_date_time.month }}{{ ansible_date_time.day }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
#          ecr_password="{{ ecr_results.stdout.split(' ')[5] }}"
#          ecr_registry="{{ ecr_results.stdout.split(' ')[8] }}"

    - name: Docker login
      docker_login:
          username: "{{ treescale_user }}"
          password: "{{ treescale_password }}"
          registry_url: "{{ treescale_repo }}"

# Ansible 2.1.2.0 broken docker_image. Cant properly tag images
#      docker_image:
#        name: "{{ item[0] }}/{{ item[1].name }}"
#        tag: "{{ item[1].tag }}"
#        path: "/etc/ansible/playbooks/docker/{{ item[1].name }}"
#        force: true
#        pull: true
#        state: present
#
    - name: Build Docker images from Dockerfile
      shell: docker build --pull -t "{{ item[0] }}/{{ item[1].name }}:{{ item[1].tag }}" .
      args:
          chdir: "{{ base_dir }}/{{ item[1].name }}"
      with_nested:
          - [
              # '{{ treescale_user }}',
              "{{ treescale_repo }}/{{ treescale_user }}"
            ]
          - [
              { name: "{{ IMAGE }}", tag: latest },
              { name: "{{ IMAGE }}", tag: "{{ date_tag }}" }
            ]

    - name: Pushing docker images
      shell: docker push "{{ item[0] }}/{{ item[1].name }}:{{ item[1].tag }}"
      with_nested:
          - [
              # '{{ treescale_user }}',
              "{{ treescale_repo }}/{{ treescale_user }}"
            ]
          - [
              { name: "{{ IMAGE }}", tag: latest, directory: "{{ IMAGE }}" },
              { name: "{{ IMAGE }}", tag: "{{ date_tag }}", directory: "{{ IMAGE }}" }
            ]

